version: "2"
services:
  wpdb:
    image: mariadb
    container_name: "${WORDPRESS_DB_NAME}"
    ports:
      - "8081:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${WORDPRESS_ROOT_PASSWORD}"
  wp:
    image: wordpress
    container_name: "${WORDPRESS_NAME}"
    volumes:
      - ./www/html:/var/www/html
    ports:
      - "8080:80"
    links:
      - wpdb:mysql
    environment:
      WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
